"""create_2 user model

Revision ID: 11672e4b0677
Revises: a63b63ce13b7
Create Date: 2023-03-02 01:10:39.595057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11672e4b0677'
down_revision = 'a63b63ce13b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
